## Model

"""
    GLMSBM

A generative model for graphs with node features, which combines a Generalized Linear Model with a Stochastic Block Model.

Reference: <https://arxiv.org/abs/2303.09995>

# Fields

- `N`: graph size
- `M`: feature dimension
- `c`: average degree
- `λ`: SNR of the communities
- `ρ`: fraction of nodes revealed
"""
struct GLMSBM{R<:Real} <: AbstractSBM
    N::Int
    M::Int
    c::R
    λ::R
    ρ::R

    function GLMSBM(; N::Integer, M::Integer, c::R1, λ::R2, ρ::R3) where {R1,R2,R3}
        R = promote_type(R1, R2, R3)
        return new{R}(N, M, c, λ, ρ)
    end
end

average_degree(glmsbm::GLMSBM) = glmsbm.c
communities_snr(glmsbm::GLMSBM) = glmsbm.λ

## Latents

"""
    GLMSBMLatents

The hidden variables generated by sampling from a [`GLMSBM`](@ref).

# Fields

- `w::Vector`: feature weights, length `M`
- `s::Vector`: community assignments, length `N`
"""
@kwdef struct GLMSBMLatents{R<:Real}
    w::Vector{R}
    s::Vector{Int}
end

## Observations

"""
    GLMSBMObservations

The observations generated by sampling from a [`GLMSBM`](@ref).

# Fields
- `A::AbstractMatrix`: symmetric boolean adjacency matrix, size `(N, N)`
- `g::AbstractGraph`: undirected unweighted graph generated from `A`
- `F::Matrix`: feature matrix, size `(M, N)`
- `Ξ::Vector`: revealed communities `±1` for a fraction of nodes and `0` for the rest, length `N`
"""
@kwdef struct ContextualSBMObservations{
    R<:Real,M<:AbstractMatrix{Bool},G<:AbstractGraph{Int}
}
    A::M
    g::G
    F::Matrix{R}
    Ξ::Vector{Int}
end
